### SERVER CONFIGURATION ###
# Base path for REST APIs
server.servlet.context-path=/Foyer2324
server.port=8089

### DATABASE CONFIGURATION ###
spring.datasource.url=jdbc:mysql://mysqlDb:3306/foyer\
?createDatabaseIfNotExist=true\
&useUnicode=true\
&useJDBCCompliantTimezoneShift=true\
&useLegacyDatetimeCode=false\
&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

### LOGGING CONFIGURATION ###
# Log file location
logging.file.name=logs/Foyer2324.log

# Logging levels
logging.level.com.xxx=warn
logging.level.org.springframework=warn

# Console log pattern
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %level [%logger{60}] - %msg%n
