version: '3.5'
services:
  app:
    build: .
    ports:
      - "8089:8089"
    container_name: app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/foyer?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
    networks:
      - foyer-network

  db:
    image: mysql:8.0
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=foyer
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - foyer-network

volumes:
  mysql-data:

networks:
  foyer-network:
    driver: bridge